# Generated by Django 3.2.8 on 2021-10-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_courts_parks'),
        ('pickup', '0002_player'),
    ]

    operations = [
    ]
