# Generated by Django 3.2.8 on 2021-10-26 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0003_merge_0002_courts_parks_0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='parks',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='parks',
            constraint=models.UniqueConstraint(fields=('name', 'street', 'city', 'state', 'zipcode'), name='pickup_parks_unique'),
        ),
    ]
