# Generated by Django 3.2.8 on 2021-11-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_auto_20211028_2113'),
        ('pickup', '0004_auto_20211025_2326'),
    ]

    operations = [
    ]
