# Generated by Django 3.2.8 on 2021-11-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0005_merge_20211103_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reciever', to='pickup.player'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='pickup.player'),
        ),
    ]
