# Generated by Django 3.2.8 on 2021-11-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_auto_20211102_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
