# Generated by Django 3.2.8 on 2021-11-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0007_schedule_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='pickup_schedule_unique',
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('player', 'park', 'time', 'date'), name='pickup_schedule_unique'),
        ),
    ]
