# Generated by Django 3.2.8 on 2021-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_auto_20211104_1216'),
        ('pickup', '0008_auto_20211103_2330'),
    ]

    operations = [
    ]
