# Generated by Django 3.2.8 on 2021-11-04 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0009_merge_0006_auto_20211104_1216_0008_auto_20211103_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
