# Generated by Django 3.2.8 on 2021-11-09 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0009_merge_0006_auto_20211104_1216_0008_auto_20211103_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteParks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pickup.parks')),
                ('player', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoriteparks',
            constraint=models.UniqueConstraint(fields=('player', 'park'), name='pickup_favoriteparks_unique'),
        ),
    ]
