# Generated by Django 3.2.8 on 2021-11-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0010_auto_20211109_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
