# Generated by Django 3.2.8 on 2021-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0010_messages_time_sent'),
        ('pickup', '0011_player_is_public'),
    ]

    operations = [
    ]
