# Generated by Django 3.2.8 on 2021-11-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0012_auto_20211116_1944'),
        ('pickup', '0012_merge_0010_messages_time_sent_0011_player_is_public'),
    ]

    operations = [
    ]
